version: "3.9"
services:
  nginx:
    build: nginx
    user: "nginx"
    container_name: webapp-nginx
    restart: always
    volumes:
      - ./nginx/default.conf:/tmp/default.conf
    environment: 
      - FLASK_SERVER_ADDR=web_user:5000      
    ports:
      - "80:80"      
    networks:
      - external
    depends_on:
      - web_user
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:80/users || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    command: /app/start.sh
  web_user:
    build: .
    container_name: webapp-user
    volumes:
      - .:/usr/src/app
    environment:
      FLASK_DEBUG: True
    networks:
      - internal
      - external
    ports: 
      - '5000:5000'
    healthcheck:
      test: ["CMD-SHELL", "curl --silent --fail localhost:5000/users || exit 1"]
      interval: 10s
      timeout: 10s
      retries: 3
    # flask requires SIGINT to stop gracefully
    # (default stop signal from Compose is SIGTERM)
    stop_signal: SIGINT      
    command: gunicorn -w 3 -t 60 -b 0.0.0.0:5000 services.user:app
networks:
  internal:
    driver: bridge
  external:
    driver: bridge